"""
Strategy management API endpoints (V5.0-A-3 backend).

Provides REST endpoints for strategy listing, validation, template generation,
and on-demand backtest execution via the platform APIRouter.
"""
from __future__ import annotations

import ast
import textwrap
import traceback
from typing import Any, Dict, List, Optional

from src.platform.api.router import APIRouter, RequestContext, ResponseContext
from src.core.logger import get_logger

logger = get_logger("platform.api.strategy")

strategy_router = APIRouter()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _get_registry() -> Dict[str, Any]:
    """Lazy-load strategy registry to avoid circular imports."""
    from src.backtest.strategy_modules import STRATEGY_REGISTRY
    return STRATEGY_REGISTRY


def _strategy_summary(name: str, module: Any) -> Dict[str, Any]:
    """Summarise a strategy module for the API response."""
    params = {}
    if hasattr(module, "param_defs"):
        for pd_item in module.param_defs:
            params[pd_item.name] = {
                "type": pd_item.type.__name__ if hasattr(pd_item, "type") else "float",
                "default": pd_item.default if hasattr(pd_item, "default") else None,
            }
    elif hasattr(module, "coerce"):
        # Fallback: extract from coerce defaults
        try:
            defaults = module.coerce({})
            params = {k: {"type": type(v).__name__, "default": v} for k, v in defaults.items()}
        except Exception:
            pass
    return {
        "name": name,
        "description": getattr(module, "description", ""),
        "params": params,
    }


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@strategy_router.get("/api/v2/strategies")
def list_strategies(req: RequestContext) -> ResponseContext:
    """List all registered strategies with parameter schemas."""
    registry = _get_registry()
    items = [_strategy_summary(n, m) for n, m in sorted(registry.items())]
    return ResponseContext(body={
        "ok": True,
        "count": len(items),
        "strategies": items,
    })


@strategy_router.get("/api/v2/strategies/{name}")
def get_strategy(req: RequestContext) -> ResponseContext:
    """Get details for a single strategy."""
    name = req.path_params.get("name", "")
    registry = _get_registry()
    if name not in registry:
        return ResponseContext(status_code=404, body={"ok": False, "error": f"Strategy '{name}' not found"})
    return ResponseContext(body={"ok": True, "strategy": _strategy_summary(name, registry[name])})


@strategy_router.get("/api/v2/strategies/templates/{name}")
def get_template(req: RequestContext) -> ResponseContext:
    """Generate a strategy code template based on an existing strategy."""
    name = req.path_params.get("name", "")
    registry = _get_registry()
    if name not in registry:
        return ResponseContext(status_code=404, body={"ok": False, "error": f"Strategy '{name}' not found"})
    module = registry[name]
    params_block = ""
    try:
        defaults = module.coerce({})
        params_block = "\n".join(f"    {k} = {repr(v)}" for k, v in defaults.items())
    except Exception:
        params_block = "    # Add parameters here"
    template = textwrap.dedent(f"""\
    # Strategy template based on: {name}
    # Generated by Unified Quant Platform V5.0

    import backtrader as bt

    class My{name.replace('_', ' ').title().replace(' ', '')}Strategy(bt.Strategy):
        params = (
    {params_block}
        )

        def __init__(self):
            self.order = None
            # Add your indicators here

        def next(self):
            if self.order:
                return
            # Add your trading logic here
            pass
    """)
    return ResponseContext(body={"ok": True, "template": template, "strategy": name})


@strategy_router.post("/api/v2/strategies/validate")
def validate_strategy(req: RequestContext) -> ResponseContext:
    """Validate strategy Python code (AST parse check)."""
    body = req.body or {}
    code = body.get("code", "")
    if not code:
        return ResponseContext(status_code=400, body={"ok": False, "error": "Missing 'code' field"})
    errors: List[Dict[str, Any]] = []
    try:
        tree = ast.parse(code)
        # Check for dangerous imports
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    if alias.name in ("os", "subprocess", "shutil", "sys"):
                        errors.append({
                            "line": node.lineno,
                            "message": f"Import '{alias.name}' is restricted in strategy code",
                            "severity": "warning",
                        })
            elif isinstance(node, ast.ImportFrom):
                if node.module and node.module.split(".")[0] in ("os", "subprocess", "shutil"):
                    errors.append({
                        "line": node.lineno,
                        "message": f"Import from '{node.module}' is restricted in strategy code",
                        "severity": "warning",
                    })
    except SyntaxError as e:
        errors.append({
            "line": e.lineno or 1,
            "message": str(e.msg),
            "severity": "error",
        })
    valid = not any(e["severity"] == "error" for e in errors)
    return ResponseContext(body={"ok": True, "valid": valid, "errors": errors})


@strategy_router.post("/api/v2/strategies/run")
def run_strategy(req: RequestContext) -> ResponseContext:
    """Run a backtest for a given strategy and return metrics."""
    body = req.body or {}
    strategy = body.get("strategy")
    if not strategy:
        return ResponseContext(status_code=400, body={"ok": False, "error": "Missing 'strategy' field"})
    symbols = body.get("symbols", [])
    if not symbols:
        return ResponseContext(status_code=400, body={"ok": False, "error": "Missing 'symbols' field"})
    start = body.get("start", "2024-01-01")
    end = body.get("end", "2024-12-31")
    params = body.get("params", {})
    cash = float(body.get("cash", 100000))
    commission = float(body.get("commission", 0.001))
    slippage = float(body.get("slippage", 0.001))

    try:
        from src.backtest.engine import BacktestEngine
        engine = BacktestEngine()
        result = engine.run_strategy(
            strategy=strategy,
            symbols=symbols,
            start=start,
            end=end,
            params=params,
            cash=cash,
            commission=commission,
            slippage=slippage,
        )
        # Remove non-serializable keys
        clean = {k: v for k, v in result.items()
                 if k not in ("nav", "_cerebro", "_quality_report", "_data_fingerprint")}
        # Convert numpy/pandas types
        for k, v in clean.items():
            if hasattr(v, "item"):
                clean[k] = v.item()
        return ResponseContext(body={"ok": True, "metrics": clean})
    except KeyError as e:
        return ResponseContext(status_code=404, body={"ok": False, "error": str(e)})
    except Exception as e:
        logger.error("strategy_run_failed", error=str(e))
        return ResponseContext(status_code=500, body={
            "ok": False,
            "error": str(e),
            "traceback": traceback.format_exc().split("\n")[-3:],
        })
