"""
Strategy Scaffold Generator (V5.0-D-2/F-3) — Code generation for new strategies, factors, and data sources.

Usage:
    python -m src.cli.scaffold strategy my_strat --template trend_following
    python -m src.cli.scaffold factor pe_adjusted --template fundamental
"""
from __future__ import annotations

import os
from datetime import datetime
from pathlib import Path
from typing import Optional

try:
    import click
    HAS_CLICK = True
except ImportError:
    HAS_CLICK = False

# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

_STRATEGY_TEMPLATE = '''"""
{name} Strategy

Auto-generated by quant scaffold on {date}.
Template: {template}
"""
from __future__ import annotations

from typing import Dict
import pandas as pd

from src.core.strategy_base import BaseStrategy


class {class_name}(BaseStrategy):
    """
    {name} strategy.

    Parameters:
        {param_doc}
    """

    name = "{name}"
    default_params = {default_params}

    def generate_signals(self, data: Dict[str, pd.DataFrame]) -> Dict[str, float]:
        """Generate trading signals.

        Args:
            data: Dict mapping symbol to OHLCV DataFrame.

        Returns:
            Dict mapping symbol to signal strength (-1.0 to 1.0).
        """
        signals = {{}}
        for symbol, df in data.items():
            if len(df) < 20:
                signals[symbol] = 0.0
                continue
            # TODO: implement signal logic
            signals[symbol] = 0.0
        return signals
'''

_STRATEGY_TEST_TEMPLATE = '''"""Tests for {name} strategy."""
import pytest
import pandas as pd
import numpy as np


class Test{class_name}:
    """Test {name} strategy."""

    @pytest.fixture
    def strategy(self):
        from src.strategies.{module_name} import {class_name}
        return {class_name}()

    @pytest.fixture
    def sample_data(self):
        dates = pd.date_range("2024-01-01", periods=100, freq="D")
        np.random.seed(42)
        prices = 100 + np.cumsum(np.random.randn(100) * 0.5)
        return {{
            "600519.SH": pd.DataFrame({{
                "open": prices * 0.99,
                "high": prices * 1.01,
                "low": prices * 0.98,
                "close": prices,
                "volume": np.random.randint(1000, 10000, 100),
            }}, index=dates)
        }}

    def test_generate_signals_returns_dict(self, strategy, sample_data):
        signals = strategy.generate_signals(sample_data)
        assert isinstance(signals, dict)
        assert "600519.SH" in signals

    def test_signal_range(self, strategy, sample_data):
        signals = strategy.generate_signals(sample_data)
        for v in signals.values():
            assert -1.0 <= v <= 1.0

    def test_empty_data(self, strategy):
        signals = strategy.generate_signals({{}})
        assert signals == {{}}
'''

_FACTOR_TEMPLATE = '''"""
{name} Factor

Auto-generated by quant scaffold on {date}.
"""
from __future__ import annotations

from typing import Optional
import pandas as pd


class {class_name}:
    """
    {name} factor.

    Computes factor values from OHLCV + fundamental data.
    """

    name = "{name}"

    def __init__(self, **params):
        self.params = params

    def compute(self, df: pd.DataFrame) -> pd.Series:
        """Compute factor values.

        Args:
            df: DataFrame with OHLCV columns.

        Returns:
            Series of factor values aligned to df index.
        """
        # TODO: implement factor computation
        return pd.Series(0.0, index=df.index, name=self.name)
'''

# ---------------------------------------------------------------------------
# Default parameters per template
# ---------------------------------------------------------------------------

_TEMPLATE_PARAMS = {
    "trend_following": {"fast_period": 10, "slow_period": 30, "threshold": 0.01},
    "mean_reversion": {"lookback": 20, "entry_zscore": 2.0, "exit_zscore": 0.5},
    "ml_factor": {"n_estimators": 100, "lookback": 60, "retrain_freq": 20},
    "momentum": {"period": 20, "top_n": 5},
    "breakout": {"period": 20, "atr_mult": 2.0},
    "fundamental": {"metric": "pe_ratio", "threshold": 15.0},
}


def _to_class_name(snake: str) -> str:
    return "".join(w.capitalize() for w in snake.split("_"))


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------

class ScaffoldGenerator:
    """Code scaffold generator."""

    def __init__(self, base_dir: Optional[str] = None):
        self.base_dir = Path(base_dir) if base_dir else Path.cwd()

    def generate_strategy(
        self,
        name: str,
        template: str = "trend_following",
        output_dir: Optional[str] = None,
    ) -> dict:
        """Generate a strategy module + test file.

        Returns:
            Dict with paths of generated files.
        """
        class_name = _to_class_name(name)
        module_name = name.lower().replace("-", "_")
        params = _TEMPLATE_PARAMS.get(template, {"param1": 0})
        param_doc = "\n        ".join(f"{k}: {type(v).__name__} (default={v})" for k, v in params.items())

        strat_dir = Path(output_dir) if output_dir else self.base_dir / "src" / "strategies"
        test_dir = strat_dir.parent / "tests" if output_dir else self.base_dir / "tests"
        strat_dir.mkdir(parents=True, exist_ok=True)
        test_dir.mkdir(parents=True, exist_ok=True)

        strat_path = strat_dir / f"{module_name}.py"
        test_path = test_dir / f"test_{module_name}.py"

        strat_content = _STRATEGY_TEMPLATE.format(
            name=name,
            class_name=class_name,
            template=template,
            date=datetime.now().strftime("%Y-%m-%d"),
            default_params=repr(params),
            param_doc=param_doc,
        )

        test_content = _STRATEGY_TEST_TEMPLATE.format(
            name=name,
            class_name=class_name,
            module_name=module_name,
        )

        strat_path.write_text(strat_content, encoding="utf-8")
        test_path.write_text(test_content, encoding="utf-8")

        return {
            "strategy": str(strat_path),
            "test": str(test_path),
        }

    def generate_factor(
        self,
        name: str,
        output_dir: Optional[str] = None,
    ) -> dict:
        """Generate a factor module.

        Returns:
            Dict with paths of generated files.
        """
        class_name = _to_class_name(name)
        module_name = name.lower().replace("-", "_")

        factor_dir = Path(output_dir) if output_dir else self.base_dir / "src" / "pipeline"
        factor_dir.mkdir(parents=True, exist_ok=True)

        factor_path = factor_dir / f"{module_name}.py"
        content = _FACTOR_TEMPLATE.format(
            name=name,
            class_name=class_name,
            date=datetime.now().strftime("%Y-%m-%d"),
        )
        factor_path.write_text(content, encoding="utf-8")
        return {"factor": str(factor_path)}

    def list_templates(self) -> list:
        """List available scaffold templates."""
        return list(_TEMPLATE_PARAMS.keys())


# ---------------------------------------------------------------------------
# Click CLI
# ---------------------------------------------------------------------------

if HAS_CLICK:

    @click.group()
    def scaffold():
        """Code scaffold generator."""
        pass

    @scaffold.command("strategy")
    @click.argument("name")
    @click.option("--template", "-t", default="trend_following",
                  type=click.Choice(list(_TEMPLATE_PARAMS.keys())),
                  help="Template type")
    @click.option("--output-dir", "-o", default=None, help="Output directory")
    def gen_strategy(name, template, output_dir):
        """Generate a new strategy scaffold."""
        gen = ScaffoldGenerator()
        result = gen.generate_strategy(name, template, output_dir)
        click.echo(f"Generated strategy: {result['strategy']}")
        click.echo(f"Generated test:     {result['test']}")

    @scaffold.command("factor")
    @click.argument("name")
    @click.option("--output-dir", "-o", default=None, help="Output directory")
    def gen_factor(name, output_dir):
        """Generate a new factor scaffold."""
        gen = ScaffoldGenerator()
        result = gen.generate_factor(name, output_dir)
        click.echo(f"Generated factor: {result['factor']}")

    @scaffold.command("templates")
    def list_templates():
        """List available templates."""
        gen = ScaffoldGenerator()
        for name in gen.list_templates():
            params = _TEMPLATE_PARAMS[name]
            click.echo(f"  {name:20s}  params: {params}")


__all__ = ["ScaffoldGenerator"]
