"""
XtQuant/QMT Gateway - 讯投QMT实盘交易网关

Implements live trading connection via XtQuant SDK (QMT/MiniQMT).
This is the highest priority gateway for individual traders.

V3.2.0: Initial release

Features:
- Connection to QMT/MiniQMT terminal
- Order submission (limit, market)
- Order cancellation
- Account/Position queries
- Trade/Order callback handling
- Auto-reconnection

Dependencies:
- xtquant (provided by broker/QMT terminal)
- Running QMT/MiniQMT terminal with API enabled

Usage:
    >>> from src.gateways import XtQuantGateway, GatewayConfig
    >>> from queue import Queue
    >>> 
    >>> config = GatewayConfig(
    ...     account_id="YOUR_ACCOUNT",
    ...     broker="xtquant",
    ...     terminal_type="QMT",  # or "MiniQMT"
    ... )
    >>> 
    >>> event_queue = Queue()
    >>> gateway = XtQuantGateway(config, event_queue)
    >>> 
    >>> # Connect
    >>> gateway.connect()
    >>> 
    >>> # Send order
    >>> order_id = gateway.send_order(
    ...     symbol="600519.SH",
    ...     side="buy",
    ...     quantity=100,
    ...     price=1800.0,
    ... )
    >>> 
    >>> # Query account
    >>> account = gateway.query_account()
    >>> 
    >>> # Disconnect
    >>> gateway.disconnect()

References:
- BigQuant QMT教程: https://bigquant.com/wiki/doc/Ux2t1gwmNn
- ThinkTrader文档: https://dict.thinktrader.net/nativeApi/
- XtQuant API文档 (provided with terminal)
"""
from __future__ import annotations

import os
import threading
import time
from datetime import datetime
from queue import Queue
from typing import Any, Dict, List, Optional

from src.gateways.base_live_gateway import (
    BaseLiveGateway,
    GatewayConfig,
    GatewayStatus,
    OrderStatus,
    OrderType,
    OrderSide,
    OrderRequest,
    OrderUpdate,
    TradeUpdate,
    AccountUpdate,
    PositionUpdate,
    GatewayEventType,
)
from src.gateways.mappers import SymbolMapper, OrderMapper


# Check if xtquant is available
# Type hints use Any when SDK not installed
XTQUANT_AVAILABLE = False
xttrader = None
xtdata = None

try:
    from xtquant import xttrader  # type: ignore
    from xtquant import xtdata  # type: ignore
    from xtquant.xttrader import XtQuantTrader, XtQuantTraderCallback  # type: ignore
    from xtquant.xttype import StockAccount  # type: ignore
    XTQUANT_AVAILABLE = True
except ImportError:
    pass  # Use stub mode


class XtQuantGateway(BaseLiveGateway):
    """
    XtQuant/QMT实盘交易网关
    
    通过xtquant SDK连接QMT/MiniQMT终端进行实盘交易。
    
    Connection Flow:
    1. Ensure QMT/MiniQMT terminal is running with API enabled
    2. Create gateway with account configuration
    3. Call connect() to establish connection
    4. Gateway automatically registers callbacks for order/trade updates
    5. Use send_order/cancel_order for trading
    6. Call disconnect() when done
    
    Thread Model:
    - Main thread: Order submission, queries
    - Callback thread: Order/Trade update handling (from xtquant)
    - Heartbeat thread: Connection monitoring
    
    Order ID Mapping:
    - client_order_id: Generated by gateway (XTQUANT-00000001)
    - broker_order_id: Returned by xtquant (order_id from API)
    
    Attributes:
        config: Gateway configuration
        trader: XtQuantTrader instance
        account: StockAccount instance
    """
    
    def __init__(
        self,
        config: GatewayConfig,
        event_queue: Queue,
        logger=None,
    ):
        """
        Initialize XtQuant gateway.
        
        Args:
            config: Gateway configuration with account_id
            event_queue: Queue for event publishing
            logger: Optional logger instance
        
        Raises:
            ImportError: If xtquant is not available
        """
        super().__init__(config, event_queue, logger)
        
        if not XTQUANT_AVAILABLE:
            raise ImportError(
                "xtquant package not available. Please ensure QMT/MiniQMT "
                "terminal is installed and xtquant is in your Python path."
            )
        
        # XtQuant instances (Any type for SDK objects)
        self._trader: Any = None
        self._account: Any = None
        self._callback: Optional["_XtQuantCallback"] = None
        
        # Terminal session path (for MiniQMT)
        self._session_path = config.terminal_path or ""
        
        # Pending orders for callback resolution
        self._pending_orders: Dict[str, OrderRequest] = {}
        self._lock = threading.Lock()
        
        self.log.info(
            "xtquant_gateway_initialized",
            terminal_type=config.terminal_type,
            account_id=config.account_id,
        )
    
    # ---------------------------------------------------------------------------
    # Connection Management
    # ---------------------------------------------------------------------------
    
    def _do_connect(self) -> bool:
        """
        Connect to QMT/MiniQMT terminal.
        
        Connection steps:
        1. Create XtQuantTrader instance
        2. Set callback handler
        3. Start trader
        4. Connect to account
        
        Returns:
            True if connection successful
        """
        try:
            # Create callback handler
            self._callback = _XtQuantCallback(self)
            
            # Create trader instance
            # For MiniQMT, need to specify session path
            if self.config.terminal_type.upper() == "MINIQMT":
                self._trader = XtQuantTrader(
                    self._session_path, 
                    self._callback
                )
            else:
                self._trader = XtQuantTrader(self._callback)
            
            # Start trader (non-blocking)
            self._trader.start()
            
            # Create account
            self._account = StockAccount(
                self.config.account_id,
                "STOCK"  # Account type
            )
            
            # Connect account
            connect_result = self._trader.connect(self._account)
            
            if connect_result == 0:
                self.log.info(
                    "xtquant_connected",
                    account=self.config.account_id,
                )
                
                # Subscribe to account events
                self._subscribe_account()
                
                return True
            else:
                self.log.error(
                    "xtquant_connect_failed",
                    result=connect_result,
                )
                return False
                
        except Exception as e:
            self.log.error(
                "xtquant_connect_error",
                error=str(e),
            )
            return False
    
    def _do_disconnect(self) -> None:
        """Disconnect from QMT terminal."""
        try:
            if self._trader:
                self._trader.stop()
                self._trader = None
            
            self._account = None
            self._callback = None
            
            self.log.info("xtquant_disconnected")
            
        except Exception as e:
            self.log.error("xtquant_disconnect_error", error=str(e))
    
    def _subscribe_account(self) -> None:
        """Subscribe to account updates."""
        if not self._trader or not self._account:
            return
        
        try:
            # Subscribe to order updates
            self._trader.subscribe(self._account)
            self.log.debug("xtquant_subscribed_account")
        except Exception as e:
            self.log.warning("xtquant_subscribe_error", error=str(e))
    
    def _do_heartbeat(self) -> None:
        """Heartbeat check for connection health."""
        # xtquant handles heartbeat internally
        pass
    
    # ---------------------------------------------------------------------------
    # Order Management
    # ---------------------------------------------------------------------------
    
    def _do_send_order(self, request: OrderRequest) -> str:
        """
        Send order via xtquant.
        
        Args:
            request: Order request with symbol, side, price, quantity
            
        Returns:
            broker_order_id from xtquant
        """
        if not self._trader or not self._account:
            raise RuntimeError("Gateway not connected")
        
        # Convert symbol to xtquant format
        xt_symbol = SymbolMapper.to_xtquant(request.symbol)
        
        # Convert order type
        xt_order_type = OrderMapper.order_type_to_xtquant(request.order_type)
        
        # Convert side
        xt_side = OrderMapper.side_to_xtquant(request.side)
        
        # Store pending order for callback resolution
        with self._lock:
            self._pending_orders[request.client_order_id] = request
        
        try:
            # Call xtquant order API
            # API signature: order_stock(account, stock_code, order_type, order_volume, price_type, price)
            if request.order_type == OrderType.MARKET:
                # Market order - use current price or 0
                order_id = self._trader.order_stock(
                    self._account,
                    xt_symbol,
                    xt_side,  # 23=买入, 24=卖出
                    int(request.quantity),
                    xt_order_type,  # 价格类型
                    0.0,  # 市价单价格为0
                    request.client_order_id,  # 策略名/备注
                    request.client_order_id,  # order_remark
                )
            else:
                # Limit order
                order_id = self._trader.order_stock(
                    self._account,
                    xt_symbol,
                    xt_side,
                    int(request.quantity),
                    xt_order_type,
                    float(request.price),
                    request.client_order_id,
                    request.client_order_id,
                )
            
            # order_id is the broker order ID (string or int depending on version)
            broker_order_id = str(order_id) if order_id else ""
            
            self.log.info(
                "xtquant_order_sent",
                client_order_id=request.client_order_id,
                broker_order_id=broker_order_id,
                symbol=xt_symbol,
                side=request.side.value,
                quantity=request.quantity,
                price=request.price,
            )
            
            return broker_order_id
            
        except Exception as e:
            with self._lock:
                self._pending_orders.pop(request.client_order_id, None)
            raise RuntimeError(f"Order submission failed: {e}")
    
    def _do_cancel_order(
        self, 
        broker_order_id: str, 
        client_order_id: str
    ) -> bool:
        """
        Cancel order via xtquant.
        
        Args:
            broker_order_id: Broker's order ID
            client_order_id: Client's order ID
            
        Returns:
            True if cancel request sent successfully
        """
        if not self._trader or not self._account:
            raise RuntimeError("Gateway not connected")
        
        try:
            # Call xtquant cancel API
            # API signature: cancel_order_stock(account, order_id)
            result = self._trader.cancel_order_stock(
                self._account,
                int(broker_order_id),
            )
            
            self.log.info(
                "xtquant_cancel_sent",
                client_order_id=client_order_id,
                broker_order_id=broker_order_id,
                result=result,
            )
            
            return result == 0
            
        except Exception as e:
            self.log.error(
                "xtquant_cancel_error",
                broker_order_id=broker_order_id,
                error=str(e),
            )
            raise
    
    # ---------------------------------------------------------------------------
    # Query Methods
    # ---------------------------------------------------------------------------
    
    def _do_query_account(self) -> Optional[AccountUpdate]:
        """Query account information from xtquant."""
        if not self._trader or not self._account:
            return None
        
        try:
            # Query account assets
            # API: query_stock_asset(account)
            asset = self._trader.query_stock_asset(self._account)
            
            if asset:
                return AccountUpdate(
                    account_id=self.config.account_id,
                    cash=float(getattr(asset, 'cash', 0)),
                    available=float(getattr(asset, 'available_cash', 0)),
                    frozen=float(getattr(asset, 'frozen_cash', 0)),
                    margin=float(getattr(asset, 'margin', 0)),
                    equity=float(getattr(asset, 'total_asset', 0)),
                    unrealized_pnl=float(getattr(asset, 'floating_pnl', 0)),
                    realized_pnl=float(getattr(asset, 'realized_pnl', 0)),
                )
            
            return None
            
        except Exception as e:
            self.log.error("xtquant_query_account_error", error=str(e))
            return None
    
    def _do_query_positions(self) -> List[PositionUpdate]:
        """Query all positions from xtquant."""
        if not self._trader or not self._account:
            return []
        
        try:
            # Query positions
            # API: query_stock_positions(account)
            positions = self._trader.query_stock_positions(self._account)
            
            result = []
            if positions:
                for pos in positions:
                    symbol = SymbolMapper.from_xtquant(
                        getattr(pos, 'stock_code', '')
                    )
                    
                    update = PositionUpdate(
                        symbol=symbol,
                        total_quantity=float(getattr(pos, 'volume', 0)),
                        available_quantity=float(getattr(pos, 'can_use_volume', 0)),
                        frozen_quantity=float(getattr(pos, 'frozen_volume', 0)),
                        yesterday_quantity=float(getattr(pos, 'yesterday_volume', 0)),
                        today_quantity=float(getattr(pos, 'today_volume', 0)),
                        avg_price=float(getattr(pos, 'open_price', 0)),
                        cost=float(getattr(pos, 'cost_price', 0)),
                        market_value=float(getattr(pos, 'market_value', 0)),
                        unrealized_pnl=float(getattr(pos, 'floating_pnl', 0)),
                        realized_pnl=float(getattr(pos, 'realized_pnl', 0)),
                        last_price=float(getattr(pos, 'last_price', 0)),
                    )
                    result.append(update)
            
            return result
            
        except Exception as e:
            self.log.error("xtquant_query_positions_error", error=str(e))
            return []
    
    def _do_query_orders(self) -> List[OrderUpdate]:
        """Query open orders from xtquant."""
        if not self._trader or not self._account:
            return []
        
        try:
            # Query today's orders
            # API: query_stock_orders(account, cancelable_only=False)
            orders = self._trader.query_stock_orders(self._account, False)
            
            result = []
            if orders:
                for order in orders:
                    symbol = SymbolMapper.from_xtquant(
                        getattr(order, 'stock_code', '')
                    )
                    
                    broker_order_id = str(getattr(order, 'order_id', ''))
                    
                    # Try to find client order ID
                    client_order_id = self._broker_to_client.get(
                        broker_order_id,
                        getattr(order, 'order_remark', '') or broker_order_id
                    )
                    
                    # Map status
                    xt_status = int(getattr(order, 'order_status', 0))
                    status = OrderMapper.status_from_xtquant(xt_status)
                    
                    # Map side
                    xt_side = int(getattr(order, 'order_type', 23))
                    side = OrderMapper.side_from_xtquant(xt_side)
                    
                    update = OrderUpdate(
                        client_order_id=client_order_id,
                        broker_order_id=broker_order_id,
                        symbol=symbol,
                        side=side,
                        status=status,
                        order_type=OrderType.LIMIT,
                        price=float(getattr(order, 'price', 0)),
                        quantity=float(getattr(order, 'order_volume', 0)),
                        filled_quantity=float(getattr(order, 'traded_volume', 0)),
                        avg_fill_price=float(getattr(order, 'traded_price', 0)),
                        error_msg=getattr(order, 'status_msg', ''),
                    )
                    result.append(update)
            
            return result
            
        except Exception as e:
            self.log.error("xtquant_query_orders_error", error=str(e))
            return []
    
    # ---------------------------------------------------------------------------
    # Callback Processing (called by _XtQuantCallback)
    # ---------------------------------------------------------------------------
    
    def _process_order_callback(self, order_data: Any) -> None:
        """
        Process order callback from xtquant.
        
        Called by _XtQuantCallback.on_order_callback()
        """
        try:
            broker_order_id = str(getattr(order_data, 'order_id', ''))
            symbol = SymbolMapper.from_xtquant(
                getattr(order_data, 'stock_code', '')
            )
            
            # Find client order ID
            client_order_id = self._broker_to_client.get(
                broker_order_id,
                getattr(order_data, 'order_remark', '') or ''
            )
            
            # Check pending orders
            if not client_order_id:
                with self._lock:
                    for cid, req in self._pending_orders.items():
                        if req.symbol == symbol:
                            client_order_id = cid
                            self._pending_orders.pop(cid, None)
                            break
            
            if not client_order_id:
                client_order_id = f"UNKNOWN-{broker_order_id}"
            
            # Map status
            xt_status = int(getattr(order_data, 'order_status', 0))
            status = OrderMapper.status_from_xtquant(xt_status)
            
            # Map side
            xt_side = int(getattr(order_data, 'order_type', 23))
            side = OrderMapper.side_from_xtquant(xt_side)
            
            update = OrderUpdate(
                client_order_id=client_order_id,
                broker_order_id=broker_order_id,
                symbol=symbol,
                side=side,
                status=status,
                order_type=OrderType.LIMIT,
                price=float(getattr(order_data, 'price', 0)),
                quantity=float(getattr(order_data, 'order_volume', 0)),
                filled_quantity=float(getattr(order_data, 'traded_volume', 0)),
                avg_fill_price=float(getattr(order_data, 'traded_price', 0)),
                error_msg=getattr(order_data, 'status_msg', ''),
            )
            
            # Process update through base class
            self._on_order_update(update)
            
        except Exception as e:
            self.log.error("xtquant_order_callback_error", error=str(e))
    
    def _process_trade_callback(self, trade_data: Any) -> None:
        """
        Process trade callback from xtquant.
        
        Called by _XtQuantCallback.on_deal_callback()
        """
        try:
            trade_id = str(getattr(trade_data, 'traded_id', ''))
            broker_order_id = str(getattr(trade_data, 'order_id', ''))
            symbol = SymbolMapper.from_xtquant(
                getattr(trade_data, 'stock_code', '')
            )
            
            # Find client order ID
            client_order_id = self._broker_to_client.get(broker_order_id, '')
            
            # Map side
            xt_side = int(getattr(trade_data, 'order_type', 23))
            side = OrderMapper.side_from_xtquant(xt_side)
            
            update = TradeUpdate(
                trade_id=trade_id,
                client_order_id=client_order_id,
                broker_order_id=broker_order_id,
                symbol=symbol,
                side=side,
                price=float(getattr(trade_data, 'traded_price', 0)),
                quantity=float(getattr(trade_data, 'traded_volume', 0)),
                commission=float(getattr(trade_data, 'traded_commission', 0)),
            )
            
            # Process update through base class
            self._on_trade_update(update)
            
        except Exception as e:
            self.log.error("xtquant_trade_callback_error", error=str(e))
    
    def _process_disconnect_callback(self) -> None:
        """Handle disconnect callback from xtquant."""
        self.log.warning("xtquant_disconnect_callback")
        self._on_disconnected()


# ---------------------------------------------------------------------------
# XtQuant Callback Handler
# ---------------------------------------------------------------------------

if XTQUANT_AVAILABLE:
    
    class _XtQuantCallback(XtQuantTraderCallback):
        """
        Internal callback handler for xtquant events.
        
        Delegates all callbacks to XtQuantGateway methods.
        """
        
        def __init__(self, gateway: XtQuantGateway):
            super().__init__()
            self.gateway = gateway
        
        def on_disconnected(self):
            """Handle disconnect event."""
            self.gateway._process_disconnect_callback()
        
        def on_stock_order(self, order):
            """Handle order update."""
            self.gateway._process_order_callback(order)
        
        def on_stock_trade(self, trade):
            """Handle trade update."""
            self.gateway._process_trade_callback(trade)
        
        def on_order_error(self, order_id, error_id, error_msg):
            """Handle order error."""
            self.gateway.log.error(
                "xtquant_order_error_callback",
                order_id=order_id,
                error_id=error_id,
                error_msg=error_msg,
            )
        
        def on_cancel_error(self, order_id, error_id, error_msg):
            """Handle cancel error."""
            self.gateway.log.error(
                "xtquant_cancel_error_callback",
                order_id=order_id,
                error_id=error_id,
                error_msg=error_msg,
            )
        
        def on_order_stock_async_response(self, response):
            """Handle async order response."""
            self.gateway.log.debug(
                "xtquant_async_response",
                response=str(response),
            )
        
        def on_account_status(self, status):
            """Handle account status change."""
            self.gateway.log.info(
                "xtquant_account_status",
                status=str(status),
            )

else:
    _XtQuantCallback = None


# ---------------------------------------------------------------------------
# Exports
# ---------------------------------------------------------------------------

__all__ = [
    "XtQuantGateway",
]
