"""Generate paper-trading demo artifacts for first-time users."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.platform.api_server import APIMetrics, GatewayService, MonitorService
from src.platform.demo import run_paper_trading_demo, write_demo_report
from src.platform.job_queue import JobQueue, JobStore


def build_echarts_payload(report: Dict[str, Any], report_path: Path) -> Dict[str, Any]:
    """Build a compact JSON payload that frontend pages can render directly."""
    summary = report["summary"]
    return {
        "title": "Open Source Preview Demo",
        "description": "Paper trading workflow. Stock analysis in the web console uses real market-data providers.",
        "source_report": str(report_path),
        "kpis": [
            {"label": "Gateway", "value": "connected" if summary["gateway_connected"] else "offline"},
            {"label": "Mode", "value": summary["mode"]},
            {"label": "Filled orders", "value": summary["filled_orders"]},
            {"label": "Cancelled orders", "value": summary["cancelled_orders"]},
            {"label": "Trades", "value": summary["trades"]},
            {"label": "Unrealized PnL", "value": round(float(summary["unrealized_pnl"]), 2)},
        ],
        "series": {},
        "workflow_steps": [step["name"] for step in report["steps"]],
    }


def write_markdown_summary(report: Dict[str, Any], output_path: Path) -> Path:
    """Write a small Markdown report for README and release-note screenshots."""
    summary = report["summary"]
    lines = [
        "# Open Source Preview Demo",
        "",
        "This report is generated by `examples/one_click_demo.py` without broker SDKs.",
        "",
        "## Summary",
        "",
        f"- Gateway connected: `{summary['gateway_connected']}`",
        f"- Mode: `{summary['mode']}`",
        f"- Filled orders: `{summary['filled_orders']}`",
        f"- Cancelled orders: `{summary['cancelled_orders']}`",
        f"- Trades: `{summary['trades']}`",
        f"- Unrealized PnL: `{round(float(summary['unrealized_pnl']), 2)}`",
        "",
        "## Workflow",
        "",
    ]
    lines.extend(f"{index}. `{step['name']}`" for index, step in enumerate(report["steps"], start=1))
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return output_path


def run(output_dir: Path) -> Dict[str, str]:
    """Run the one-click demo and return generated artifact paths."""
    output_dir.mkdir(parents=True, exist_ok=True)
    queue = JobQueue(store=JobStore(), max_workers=1)
    try:
        report = run_paper_trading_demo(
            GatewayService(),
            queue=queue,
            monitor_service=MonitorService(),
            metrics=APIMetrics(),
        )
    finally:
        queue.shutdown()

    report_path = write_demo_report(report, output_dir / "platform_console_demo.json")
    echarts_payload = build_echarts_payload(report, report_path)
    echarts_path = output_dir / "web_console_echarts.json"
    echarts_path.write_text(json.dumps(echarts_payload, ensure_ascii=False, indent=2), encoding="utf-8")
    markdown_path = write_markdown_summary(report, output_dir / "demo_report.md")

    return {
        "report": str(report_path),
        "echarts": str(echarts_path.resolve()),
        "markdown": str(markdown_path.resolve()),
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate open-source paper-trading demo artifacts")
    parser.add_argument("--out-dir", default="report/open_source_demo")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    artifacts = run(Path(args.out_dir))
    print(json.dumps({"ok": True, "artifacts": artifacts}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
